### ISSUE TITLE
Only send logs which contain certain string to teams channel

### ISSUE THREAD

**Issue by robbo10** [AnesFoufa/python-teams-logger#11]
Hello,

I was wondering if it would be possible to search the logging.info message, and for example only send logs to teams channel when it includes a particular string? 

Would this work

```
import logging
from teams_logger import TeamsHandler, Office365CardFormatter

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

th = TeamsHandler(url='YOUR_WEB_HOOK_URL', level=logging.INFO)
th.setLevel(logging.DEBUG)
logger.addHandler(th)

cf = Office365CardFormatter(facts=["name", "levelname", "lineno"])
th.setFormatter(cf)
logger.info('this contains part of the string')
```

**Comment by AnesFoufa** [comment]
Hi.
I'm not sure I understand the issue. You mean log messages should be filtered before being sent to Teams?

**Comment by rnag** [comment]
I guess from my understanding, the intention is to do a regex match against the log message and only log it to teams if it matches the regex.

based on this I would suggest creating a new logger object and only using it to log messages that you don't ever want to be sent to teams. I'm assuming that would work since it doesn't have the handler that logs the messages to teams (not sure if there's an easier way that I'm missing either)

```python
logger2 = logging.getLogger(__name__ + '_test')

logger2.info('just a regular log message!')
```

**Comment by AnesFoufa** [comment]
In the python logging framework, there is a concept of filters attached to loggers and/or handlers to filter logs. 
https://docs.python.org/3/library/logging.html#filter-objects
So I think you should use the right filter with your TeamsHandler.
